### ISSUE TITLE
4.16 is out of date. 4.17 is new current.

### ISSUE THREAD

**Issue by jcfrosty** [linuxserver/docker-minetest#15]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Access denied. Reason: Your client's version is not supported.
Please contact server administrator.

Client Version 4.17
Server Version 4.16

Using UnRAID

update to minetest 4.17.1

It will work with my distrobutions packaged version of minetest.

No

**Comment by CHBMB** [comment]
It's being worked on, but is failing to build at the moment......

https://github.com/linuxserver/docker-minetest/tree/build_0.4.17.1

**Comment by kolewu** [comment]
There seems to be something wrong with the build: Despite the fact that the last released version is requested and downloaded, the build log has the following
```
-- *** Will build version 5.0.0-dev ***
...
Scanning dependencies of target GenerateVersion
-- *** Detected Git version 5.0.0-dev-a95aed8 ***
[  1%] Built target GenerateVersion
```

**Comment by kolewu** [comment]
The branch `build_0.4.17.1` builds fine on x86_64, but can't start a game based on the standard minetest game, because the game is from master and so doesn't match the engine. Since the game is not at the same minor version as the engine, you have to fetch the latest tag of the game, too.

**Comment by kolewu** [comment]
I now have the changes to build the last released version with a matching game. How are the docker repos managed, since the three platforms seem to be mostly identical. Should I prepare a pull request for this repo only or is there a master anywhere?

**Comment by sparklyballs** [comment]
i'm working on it right now

**Comment by kolewu** [comment]
Could you gave me a link to the process for changing a lsio docker image? There is another change, I want to propose: It's not necessary to copy the default games (*minetest_game* and *minmal*) to the user path. Just leave minimal where it is and install the *minetest_game* in the same directory `/usr/share/minetest/games/`.

**Comment by tobbenb** [comment]
We don't have any documentation of how to modify our image.
You clone the repository, make the changes and open a PR.
