### ISSUE TITLE
Define gameid, world and port as environment variables

### ISSUE THREAD

**Issue by hublol** [linuxserver/docker-minetest#23]
Not an issue, rather an enhancement request: would it be possible to define the gameid, world and port as environment variables. When not provided, you can default to the usual values.

This would make it possible to run multiple minetest servers, with different games/worlds, on the same server.

I saw in the code (root/etc/services.d/minetest/run) that the world name can already be defined using an environment variable, so it's just a matter of doing the same for the gameid and port.

Thanks!

**Comment by CHBMB** [comment]
There's no need to define the port as that can be changed in your docker run command or docker compose side.

You could just run multiple containers synchronously for multiple servers.

I'm not necessarily against adding `gameid` and a quick look it seems pretty straightforward.  

Just run me by the use case though, my understanding would be you'd run different containers with different `gameid` right?

**Comment by hublol** [comment]
You are right for the port, I feel dumb for asking... Without docker, the gameid, world and port are the 3 parameters I usually play with to run different servers and I didn't think beyond that!

And yes, the use case is correct, I would run multiple containers with different gameid and world parameters. But specifying the gameid would be useful even in the case of a single container.

**Comment by CHBMB** [comment]
@hublol Can you test this PR please?

Pull `lsiodev/minetest` it has a new environmental variable `GAMEID`
