### ISSUE TITLE
CLI_ARGS does not work if more than one argument is passed

### ISSUE THREAD

**Issue by bcopy** [linuxserver/docker-minetest#26]
**Host OS :** CentOS 7 / docker v18.09.7

**Description :** If you provide a CLI_ARGS env variable with space-separated arguments, the startup fails.

## Test case

Try : 
```docker run -it --rm -e CLI_ARGS="--info --help" linuxserver/minetest```

Output : 
```2019-07-12 16:25:52: ERROR[Main]: Unknown command-line parameter "--info --help"```

but if you specify a single argument it works fine :
```docker run -it --rm -e CLI_ARGS="--info" linuxserver/minetest```

I think the ```root/etc/services.d/minetest/run``` script should split the incoming string by space.
For instance (https://stackoverflow.com/questions/9293887/reading-a-delimited-string-into-an-array-in-bash)

**Comment by thelamer** [comment]
Naww just as bug we need to pull out the quotes , that will pass literal spaces

**Comment by aptalca** [comment]
fixed in #27
