### ISSUE TITLE
Missing Postgresql support

### ISSUE THREAD

**Issue by top4ek** [linuxserver/docker-minetest#29]
Minetest is missing postgresql support. As I see, minetest is compiled with no psql support. Could it be added?

------------------------------

## Expected Behavior
```
$ docker exec -it minetest minetestserver --migrate postgres --world "/config/.minetest/world"
```
Must migrate world to postgresql from sqlite3.

## Current Behavior
Fails with error report:
```
2020-03-08 11:19:30: ERROR[Main]: An unhandled exception occurred: Database backend postgres not supported.
2020-03-08 11:19:30: ERROR[Main]: In thread 7fb184f6cd00:
2020-03-08 11:19:30: ERROR[Main]: /tmp/minetest/src/main.cpp:e8: int main(int, char**): A fatal error occurred: Database backend postgres not supported.
```

## Steps to Reproduce
1. Install postgresql server and create role/database for migration
2. Try to migrate

## Environment
**OS:** Debian 10      
**CPU architecture:** x86_64      
**How docker service was installed:** from distro repo. (not sure about that)
      
## Command used to create docker container (run/create/compose/screenshot)
version: "2"
services:
  minetest:
    image: linuxserver/minetest
    container_name: minetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - /home/alex/minetest:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: unless-stopped

## Docker logs
Nothing about migration. Just game logs.

**Comment by brycied00d** [comment]
This fork from a couple years ago appears to have what's necessary to accomplish this. https://github.com/pickardjoe/docker-minetest-postgres

**Comment by top4ek** [comment]
Yep, i've see that, but it would be nice to have it in original repo :)

**Comment by thejordanclark** [comment]
I also forked this in June to add PostgreSQL support.
https://github.com/thejordanclark/docker-minetest

check the "postgresql" branch.

It has worked well for the last 10 months.  I was just going to merge in updates and build another image to update my running instances.

https://hub.docker.com/repository/docker/thejordanclark/minetest-server-postgresql

I personally like have PostgreSQL support in Minetest.  I'm not sure how many others use it that way.
