### ISSUE TITLE
Add PostgreSQL support

### ISSUE THREAD

**Issue by PeterNerlich** [linuxserver/docker-minetest#36]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Compile Minetest server with support for PostgreSQL

------------------------------

## Desired Behavior

Minetest server should work with `pgsql_connection = `... in `world.mt` as described here: https://wiki.minetest.net/Database_backends#PostgreSQL

## Current Behavior

Minetest server crashes continually:

    2021-10-29 11:00:54: ACTION[Main]: Server: Shutting down
    2021-10-29 11:00:55: ERROR[Main]: An unhandled exception occurred: Database backend postgresql not supported.
    2021-10-29 11:00:55: ERROR[Main]: In thread 7fd9c4731c00:
    2021-10-29 11:00:55: ERROR[Main]: /tmp/minetest/src/main.cpp:f3: int main(int, char**): A fatal error occurred: Database backend postgresql not supported.

## Alternatives Considered

- Switching to a different database backend. But this seems like a fundamental feature of Minetest, so I think it would be worth for the container to provide this, too.
- Creating our own dockerfile based on this one. See notes below.
- Compiling and running Minetest outside of docker. This was the original way we want to change from. We installed `libpq-dev` (header files for libpq5) and compiled minetest with `-DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/` on Ubuntu. This exact package name exists on Alpine as well, I have not yet tried whether dropping these two into the Dockerfile already does the job.

**Comment by PeterNerlich** [comment]
Ping, I would like this to remain open.

**Comment by phedders** [comment]
64 bytes from me too...

**Comment by SharkyRawr** [comment]
I made a pull request to add PostgreSQL and Prometheus if you wish to try: https://github.com/linuxserver/docker-minetest/pull/38
