### ISSUE TITLE
Upgrade to 5.5.0

### ISSUE THREAD

**Issue by riker09** [linuxserver/docker-minetest#41]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Update minetest server deps to 5.5.0

**Comment by aptalca** [comment]
GitHub sometimes likes to disable cron based workflows without any notice. This one's triggers were disabled and we had no idea. They are enabled now and a new build should trigger within the hour. Thanks for the heads up.
