### ISSUE TITLE
${CLI_ARGS} are not working

### ISSUE THREAD

**Issue by mikey0000** [linuxserver/docker-minetest#47]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
${CLI_ARGS} should be interpreted correctly 

## Current Behavior
minetestserver fails and prints options list

## Steps to Reproduce
1. Create new docker image using docker-compose
2.  Run docker logs

## Environment
**OS:** debian
**CPU architecture:** arm64
**How docker service was installed:**
followed official docker-compose instructions, however I used portainer.io to create the stack

**Comment by Code-Slave** [comment]
did you fix this. same issue

**Comment by mikey0000** [comment]
Yeah docker exec - it /bin/sh and edit the start _script_

7/12/2022 5:47:41 am CodeS1ave ***@***.***>:

**Comment by mclang** [comment]
Hello.
Tried to spin up minetest server for the first time but stumbled upon this same problem. Running e.g `minetestserver --gameid mineclone2 --info` seems to work though.

Could you @mikey0000 maybe elaborate a bit which file I need to edit and what modifications to make :pray: 

Why this is tagged as invalid @aptalca ?

**Comment by mikey0000** [comment]
```
docker exec {docker_id} -it /bin/bash
vi /etc/services.d/minetest/run
```

`exec s6-setuidgid abc minetestserver --port 30000 --config /config/.minetest/main-config/minetest.conf`

**Comment by mclang** [comment]
Okay found out the problem.

The example `docker-compose.yml` given in [README](https://github.com/linuxserver/docker-minetest#docker-compose-recommended-click-here-for-more-info) has still double-quotes around `CLI_ARGS` parameter. Problem was reported ages ago in https://github.com/linuxserver/docker-minetest/issues/30 but sadly the documentation hasn't been fixed yet :disappointed: 

Right way to pass client arguments is without quotes, e.g
```
- CLI_ARGS=--gameid minetest --port 30123 --logfile /config/.minetest/minetest-server.log --info
```

I was about to make PR for the change, but _Contributing to minetest_ discouraged me...

**Comment by aptalca** [comment]
It was marked `invalid` because the issue template was not filled out properly

I now see that the readme-vars incorrectly has quotes for the value. But if we removed the quotes, then the cli version would be incorrectly generated because our templating engine does not provide a solution for this yet.

This needs to be fixed in our jenkins-builder, which generates the templates. The fix is in the works.
