### ISSUE TITLE
Upgrade to 5.8.0

### ISSUE THREAD

**Issue by zJudGenie** [linuxserver/docker-minetest#53]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Probably GitHub disabled again the scheduled actions

### Reason for change

The new version of Minetest came out

**Comment by aptalca** [comment]
Yup, it did. I reenabled them and it should push shortly.

Thanks for the heads up.

**Comment by aptalca** [comment]
Looks like there are some breaking changes that require a build fix. We'll get a PR out.

**Comment by thelamer** [comment]
linking https://github.com/minetest/minetest_game/issues/3079

**Comment by aptalca** [comment]
#52 merged now
