### ISSUE TITLE
[BUG] upstream deprecation warning

### ISSUE THREAD

**Issue by lmaddox** [linuxserver/docker-minetest#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

deprecation warning

### Expected Behavior

should not produce warnings.

preliminary search shows that it's maybe related to [this](https://github.com/minetest/minetest/issues/12036)

### Steps To Reproduce

`./docker-compose.yml`

### Environment

```markdown
- OS: voidlinux
- How docker service was installed: distro's packagemanager; swarm manager
```

### CPU architecture

x86-64

### Docker creation

```bash
#! /usr/bin/env -S sh -c "docker compose -f \$@ up --build" shebang

services:

  minetest:
    container_name: minetest
    build: .
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - "CLI_ARGS=--gameid minetest_game --world /config/.minetest/worlds/world"
    volumes:
      - minetest-data:/config/.minetest
    network_mode:   "host"                         # 30000, 29999
    restart:        unless-stopped
    logging:
      driver:      "syslog"

volumes:
  minetest-data:
    driver: local
```

Dockerfile:

```
FROM lscr.io/linuxserver/minetest:latest
RUN apk update
RUN apk upgrade --no-cache
RUN apk add --no-cache lua-socket lua-cjson lua5.1-socket lua5.1-cjson cjson
```
```


### Container logs

```bash
minetest  | 2024-08-22 20:49:34: WARNING[Main]: MINETEST_SUBGAME_PATH is deprecated, use MINETEST_GAME_PATH instead.
```
```

**Comment by aptalca** [comment]
Thnks for the heads up.

By the way, you don't have to build your own image. You can just use our universal package install mod for those additional packages: https://github.com/linuxserver/docker-mods/tree/universal-package-install
